version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: finance_app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://finance:?dV|7y\\GY.xx@@83.147.244.119:5432/finance_db
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY:-finance-app-external-api-key}
