version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: finance_postgres
    environment:
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=finance_password
      - POSTGRES_DB=finance_db
    ports:
      - '5433:5432'    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: finance_app    
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production      
      - DATABASE_URL=postgresql://finance_user:finance_password@postgres:5432/finance_db?schema=public
