version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: finance_dev_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    name: finance_postgres_dev_data
